### ISSUE TITLE
Issue: Exception message is wrong when double values are compared

### ISSUE THREAD

**Issue by StefH** [tpierrain/NFluent#231] opened 2018-03-10 14:59 UTC
This code:
``` charp
double d = 1.0d;
Check.That(d).IsEqualTo(2.0);
```

Throws this exception:

> NFluent.FluentCheckException:
> The checked value is different from the expected one.
> The checked value:
>         [1]
> The expected value:
>         [1]
>    at NFluent.Helpers.EqualityHelper.<>c__DisplayClass4_0.<PerformEqualCheck>b__0()
>    at NFluent.Kernel.Checker`2.ExecuteNotChainableCheck(Action action, String negatedExceptionMessage)
>    at NFluent.Kernel.Checker`2.ExecuteCheck(Action action, String negatedExceptionMessage)
>    at NFluent.Helpers.EqualityHelper.PerformEqualCheck(IChecker`2 checker, Double expected)
>    at NFluent.DoubleCheckExtensions.IsEqualTo(ICheck`1 check, Double expected)

This is wrong, it should be:

**The expected value:
        [2]**

**Comment by dupdob** [comment] 2018-03-10 18:45
Thanks for taking the time to report this issue. I was able to reproduce it and fixed it.
It has been introduced in V 2.1 when error messages where improved for double. 
Fix will be available early next week (in beta)

**Comment by dupdob** [comment] 2018-03-10 18:57
It turns out that no existing test verified error messages. Now fixed

**Closed** 2018-03-10 19:01 UTC
Labels: bug

**Comment by dupdob** [comment] 2018-03-12 15:54
Beta is available there: https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent

**Comment by StefH** [comment] 2018-03-13 07:04
Can you provide a target date for the real NuGet ?

**Comment by dupdob** [comment] 2018-03-13 17:06
Next official release is schedule for (early) April. Just for clarification, **the build process for beta and stable release is the same, so there is no specific concerns using a beta** one.

_To be specific, V.2.3 will provide a new set of helper APIs to ease the implementation of custom checks. The design of those APIs is still in beta an subject to to change in name/signature until the final release. The rest of NFluent remains unaltered_.
