### ISSUE TITLE
Enumerable checks fails on IEnumerable<object> (Contains, ContainsExactly, IsEquivalentTo)

### ISSUE THREAD

**Issue by yhan** [tpierrain/NFluent#292] opened 2019-03-19 16:26 UTC
Regression on version 2.5.0 ( ContainsExactly)

```CSharp
       [Test]
        public void Awkward_behaviour_with_NFluent()
        {
            var toBeChecked = new object[]
            {
                1,
                2,
                3,
                4
            };

            IEnumerable<int> expected = Enumerable.Range(1, 4);
            
            CollectionAssert.AreEquivalent(expected, toBeChecked);  // OK 
            CollectionAssert.AreEqual(expected, toBeChecked);       // OK

            Check.That(toBeChecked).ContainsExactly(expected);      // KO ;-(
        }

```

**Comment by dupdob** [comment] 2019-03-19 19:33
Issue is reproduced. And unexpected. Working on a fix

**Comment by dupdob** [comment] 2019-03-21 07:05
Workaround identified:
you need to cast the expected value using LinQ's Cast<object>:
```csharp
[Test]
public void Awkward_behaviour_with_NFluent()
{
     var toBeChecked = new object[] {1, 2, 3,4 };
      IEnumerable<int> expected = Enumerable.Range(1, 4);
            
      Check.That(toBeChecked).ContainsExactly(expected);      // KO ;-(
      Check.That(toBeChecked).ContainsExactly(expected.Cast<object>());      // OK ;-)
}
```
A first fix has been identified, but we will not rush a release. 
Expect a new version end of March, giving us the time to perform extensive testing.

**Comment by yhan** [comment] 2019-03-21 15:18
Thanks it was exactly what we chose as workaround :-)

**Comment by dupdob** [comment] 2019-03-22 11:20
@yhan, fix looks ready. As the issue is limited and has a workaround, I propose to release the fix in the next version (2.6) which should arrive before summer.
That being said, we can also deliver a patched version. Would you be ok to test the beta and confirm the fix on your side?

**Comment by KN4CK3R** [comment] 2019-05-02 12:23
Is this the same error?
```csharp
IEnumerable<char> e1 = "test";
IEnumerable<char> e2 = "test2";

Check.That(e1).ContainsExactly(e2);
```
It fails with a NotImplementedException from ValueBlock.WithEnumerableCount().

**Comment by dupdob** [comment] 2019-05-02 12:45
Thanks for reporting this.
This is a different issue, probably due to the fact you are using strings.

**Comment by dupdob** [comment] 2019-05-02 12:58
Can you please open an issue for this? Can you please explain to me what is the expected result/what you are trying to achieve ?
I can fix the exception, but I am not sure the result will fit your expectations

**Comment by KN4CK3R** [comment] 2019-05-02 13:12
Here is the issue with more informations #299.

**Closed** 2019-06-28 21:28 UTC
Labels: bug
