### ISSUE TITLE
Check.That(1).Not.IsZero();

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#176] opened 2016-10-23 14:23 UTC
Well,

`Check.That(0).Not.IsZero();`
This breaks and this is ok.

  but:

`Check.That(1).Not.IsZero();`
Normally, this should not break !
And this breaks !

Regards.

**Comment by dupdob** [comment] 2016-10-24 07:43
Hello
which NFluent are you using? I am not able to reproduce here.
Can you try with the latest pre release?

**Comment by SilNak** [comment] 2016-10-27 06:09
1.4.0.0

**Comment by SilNak** [comment] 2016-10-27 06:17
the 2.0.0_alpha i doing the same !
![image](https://cloud.githubusercontent.com/assets/18025453/19756535/b000bcf0-9c1d-11e6-8043-84e3181f7b9e.png)

**Comment by dupdob** [comment] 2016-10-27 06:54
It looks like Not operator has not been applied. Can you please share the full test? Maybe a link to a repo?
One possibility I'd like to explore is that some other test mess with the Not operator

**Comment by dupdob** [comment] 2016-10-27 06:57
Quick stupid question: looking at your screen capture, it seems like the debugger breaks whenever a fluentcheckexception is raised, so can you make sure the debugger breaks when the exception is not handled?
The Not logic works by swallowing fluentcheckexceptions, so it is expected to have some raised during execution

**Comment by SilNak** [comment] 2016-10-27 11:02
Sorry It has been fixed in 2.0.0.alpha.

I'm Not In Debug Mode...
But it still bugged in 1.4 and also in 1.3.1.
![image](https://cloud.githubusercontent.com/assets/18025453/19764827/6d436354-9c45-11e6-9bbe-00bfe8c845fb.png)

**Comment by dupdob** [comment] 2016-10-27 11:04
I will check previous versions. Note that the screenshot your provide is ok, no error there.

**Comment by dupdob** [comment] 2016-10-27 14:28
I did a check on NFluent 1.3.1 (latest stable). This runs fine 
```csharp  
 [Test]
 // issue #176
 public void NegatedIsZero()
 {
       Check.That(1).Not.IsZero();
       Check.That(1).IsNotZero();
       Check.That(0).Not.IsNotZero();
       Check.That(0).IsZero();
 }
```

**Comment by dupdob** [comment] 2016-10-28 08:32
Ok, just seen your previous comment @SilNak. I close the issue then

**Closed by dupdob** 2016-10-28 08:32 UTC
