### ISSUE TITLE
Reflection 'Parameter count mismatch' when comparing lists

### ISSUE THREAD

**Issue by ggraham-412** [tpierrain/NFluent#238] opened 2018-04-27 13:49 UTC
The following test program fails, and the test failure reports System.Reflection.TargetParameterCountException: 'Parameter count mismatch.' 

I'm not 100% sure of the best way to compare lists in NFluent, but I'm pretty sure it shouldn't be failing with that exception.  

  Thank you!

```
public class NTest
    {
        private class TestCase
        {
            public List<int> Items { get; set; } = new List<int>();
        }

        [Fact]
        public void Test()
        {
            TestCase a = new TestCase();
            TestCase b = new TestCase();

            a.Items.Add(1);
            a.Items.Add(2);
            a.Items.Add(3);

            b.Items.Add(1);
            b.Items.Add(2);
            b.Items.Add(3);

            Check.That(a).Considering().Public.Properties.IsEqualTo(b);
        }
    }
```

**Comment by dupdob** [comment] 2018-04-27 14:01
Thanks for taking the time to report this.
I look into this right now.

**Comment by dupdob** [comment] 2018-04-27 14:13
I confirm I reproduce this issue with the latest version.

**Comment by dupdob** [comment] 2018-04-27 15:30
# Overview
The fix has been implemented, but it will not provide the result you probably expect, as it implies **ignoring** the content of the _Items_ property.
To get the result you are looking for, you should probably override the _Equals_ method of the class you want to check (_TestCase_ here).
Also, to check for enumeration, you can use **ContentsExactly(...)**, such as:
```CSharp
Check.That(a.Items).ContainsExactly(b.Items);
```
Note also that your sample works if you use arrays:
```Csharp
       public class NTest
        {
            private class TestCase
            {
                public int[] Items { get; set; }
            }

            [Fact]
            public void Test()
            {
                TestCase a = new TestCase();
                TestCase b = new TestCase();

                a.Items = new []{1, 2, 3};
                b.Items = new []{1, 2, 3};

                Check.That(a).Considering().Public.Properties.IsEqualTo(b);
            }
        }
```
# Detailed explaination
To be more specific, the fix disregards the array of _int_'s that is wrapped by the **List** class. It is because it is expressed as an _indexed property_. This leads to a crash with the current versions as NFluent try to get the content without providing an index value.
The Net reflection APIs provide no information regarding the legal values for the index; therefore the fixed version simply ignore the property, as it cannot guess the index value to be used.

# Why fixing this is complex
Assuming I find a proper way to handle indexed properties, this check will still be fragile.
for exemple, the following check fails:
```CSharp
           [Fact]
            public void Test()
            {
                TestCase a = new TestCase();
                TestCase b = new TestCase();

                a.Items.Add(1);
                a.Items.Add(2);
                a.Items.Add(3);
                // deliberately add extra items and remove them
                a.Items.Add(4);
                a.Items.Add(5);
                a.Items.Remove(4);
                a.Items.Remove(3);

                b.Items.Add(1);
                b.Items.Add(2);
                b.Items.Add(3);

                Check.That(a).Considering().Public.Properties.IsEqualTo(b);
            }
```
With an error on the _Capacity_ property:
```
The checked value's property 'Items.Capacity' does not have the expected value.
The checked value's property 'Items.Capacity':
	[8]
The expected value's property 'Items.Capacity':
	[4]
```
because adding extra entries led the _List_ class to allocate a larger array. It may be or not be the desired behaviour depending on what you are testing for.

I will create another issue to request a general solution for this problem.

**Closed by dupdob** 2018-04-27 15:30 UTC
Labels: bug
